services:
  # Service to instrument.
  tirl:
    build: .
    pid: "host"
    ports:
      - '8080:8080'
    networks:
      - otel-net

  autoinstrumenter:
    image: otel/ebpf-instrument:main
    pid: 'host'
    privileged: true
    environment:
      OTEL_EBPF_TRACE_PRINTER: text
      OTEL_EBPF_OPEN_PORT: 8080
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317   # envoyé à Tempo
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    depends_on:
      - tempo
    networks:
      - otel-net

  # Profiling CPU/mémoire
  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    privileged: true
    pid: "host"
    volumes:
      - ./config/alloy-config.alloy:/etc/alloy/config.alloy:z
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "12345:12345"
    depends_on:
      - pyroscope
      - tirl
    networks:
      - otel-net

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml:z
    ports:
      - "4317:4317"   # OTLP gRPC
      - "3200:3200"   # API Tempo
    networks:
      - otel-net

  # Backend profils
  pyroscope:
    image: grafana/pyroscope:1.18.1
    command:
      - -self-profiling.disable-push=true
      - -config.file=/etc/pyroscope.yaml
    volumes:
      - ./config/pyroscope.yaml:/etc/pyroscope.yaml:z
    ports:
      - "4040:4040"
    networks:
      - otel-net

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:z
    ports:
      - "3000:3000"
    depends_on:
      - tempo
      - pyroscope
    networks:
      - otel-net

networks:
  otel-net:
    driver: bridge